services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    ports:
      - "8182:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev